# Generated by Django 2.2.2 on 2020-07-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='内容')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '时间',
                'ordering': ['-created_time'],
            },
        ),
    ]
